language: ruby  
cache: bundler
rvm:
 - 2.2
services:
  - docker
branches:
 only:
  - master
  - stable
before_install:
 - docker pull owasp/dependency-check
 - docker run --volume $(pwd):/src --volume $(pwd):/report owasp/dependency-check --scan /src --format "ALL" --project "Cryptopus OWASP Dependency Check" --out /report
 - sudo service mysql restart
install:
 - bundle install --path vendor/bundle
before_script:
 - bundle exec rake db:create
 - bundle exec rake db:setup
 - bundle exec rake db:migrate
 - bundle exec rake geo:fetch
script:
 - bundle --deployment
 - bundle exec rake ci --trace

